# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Roby Parr
author: Roby Parr
email: roby@robyparr.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Roby Parr and I'm a Software developer with strong technical and
  concise communication skills. I'm driven to create tools that not only improve
  but also enable our work, lives, and communication. I especially love building
  apps in Ruby on Rails and am starting to dabble in frontend development with
  React and concurrent apps with Elixir.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robyparr.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: robyparr
github_username:  robyparr
version: v4.1.0
copyright: "&copy; 2018 Roby Parr"
default_date_format: "%b %-d, %Y"

# Blog
show_excerpts: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
